theme: minima
title: Build for Impact
description: Data Engineering, Advanced Analytics & AI Ideas and Patterns That Come from Practice, Not Prompts
author: Jean Hayes
url: "https://jehayesms.github.io"